# Generated by Django 2.1.5 on 2019-08-27 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_car_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='car_image',
            new_name='car_img',
        ),
    ]
